name: "Deploy to EC2"
description: "Deploy Spring Boot app to EC2"

inputs:
  host:
    required: true
  username:
    required: true
  key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy JAR
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        source: "target/*.jar"
        target: "/home/ubuntu/"

    - name: Run App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar /home/ubuntu/target/*.jar > app.log 2>&1 &
